name: BrianHalweil
favicon: null
layout_spectrum: 0.5696770385839045
typography_spectrum: 0.7747395250480622
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8823087515775114
  lightness: 0.36880972934886813
  saturation: 0.4185248683206737
  rhythmicContrast: 0.6834695166908205
purpose: []
